### ISSUE TITLE
Markdown editor breaks when applying formatting

### ISSUE THREAD

**Issue by hybridvision** [rainlab/blog-plugin#209]
**Expected Behaviour**

When editing a blog post, if you select some text, click the formatting icon and choose a heading style, that should be applied.

![image](https://cloud.githubusercontent.com/assets/11492432/16017829/f66f6f88-31a1-11e6-9271-86764bc62398.png)

**Actual Behaviour**

When selecting a heading style, nothing appears to happen but an error is logged to the console and from this point the markdown editor is broken and no longer updates the preview.

![image](https://cloud.githubusercontent.com/assets/11492432/16017865/26b913ba-31a2-11e6-8de8-26b833842b6e.png)

**Steps to reproduce**

1) Edit a blog post
2) Select some text and click the "Formatting" icon in the tool bar and choose a heading level
3) No formatting is applied and an error is logged to the console.

**OctoberCMS Build**

OctoberCMS build 345 with Rainlab Blog v1.2.7

**Other notes**

I've tested this on two different computers and two versions of the site (local and production) and the error is consistent.

**Comment by msimkunas** [comment]
I'm experiencing the same issue. Are there any workarounds until the official fix is released?

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/october/issues/2154

Excellent report, thanks for this!

**Comment by hybridvision** [comment]
Thanks @daftspunk! I'll update over the weekend :)

Really appreciate all your work on OctoberCMS!

**Comment by PanikaValecha** [comment]
Hi, 
I am facing the same issue. The fix that you said doesn't work. The display is still the same.
#Abc or ## for the heading and ** for bold doesn't work. I created a blog and when I preview, it displays the #Abc as it is instead of showing Abc as bold.

Line 94 and 95 of the markdown editor is as follows:
 var $target = $(ev.target),
            $button = $target.is('a') ? $target : $target.closest('.btn'),
      
What should I change it into?  Can you please assist me with the same?

Thanks.

**Comment by LukeTowers** [comment]
@PanikaValecha are you using the latest version of October and the blog plugin? Are you running PHP7?

**Comment by PanikaValecha** [comment]
The person for blog plugin is 1.2.16. For the blogs, I am just using simple html.
